### ISSUE TITLE
Changes to run on a device instead of browser?

### ISSUE THREAD

**Issue by tej-rana** [imsingh/auth0-ionic4-app#1]
What are the changes to make to run on a device instead of browser. Your code has redirectUrl set to http://localhost:8100. Everything you've written is basically for an angular app. 

Specifically, what should the **redirectUrl** in the app, the **Allowed Callback Url** in Auth0, Allowed origin (CORS) in Auth0 be? Do we use widget id from config.xml? You haven't even used @Auth0/Cordova library.

Why is this even called auth0-ionic4-app?

**Comment by imsingh** [comment]
@tinysnippt I understand your concern. Since Latest Ionic runs using WebServer. I had to put redirectUri to localhost. Secondly, You can still use file://* protocol Allowed origin, if you are running a cordova app. Best place to ask for these kinda question is at Auth0 Community. https://community.auth0.com/

Thanks.
